// app/anilist-redirect/page.tsx
"use client";

import Layout from "@/components/layout";
import ToastContainer from "@/components/ui/toast-container";
import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { Card, CardContent } from "@/components/ui/card";

export default function Page() {
	const router = useRouter();

	useEffect(() => {
		try {
			const urlHash: string = new URL(window.location.href).hash;
			const params: URLSearchParams = new URLSearchParams(urlHash.substring(1));
			const accessToken: string | null = params.get("access_token");

			if (accessToken) {
				saveToken(accessToken);
				router.push("/anilist-login");
			} else {
				console.error("No access token found in URL hash");
			}
		} catch (error) {
			console.error("Failed to process redirect:", error);
		}
	}, [router]);

	const saveToken = (accessToken: string): void => {
		try {
			localStorage.setItem("anilistToken", accessToken);
			const expirationTime: number = Date.now() + 24 * 60 * 60 * 1000;
			localStorage.setItem("anilistTokenExpiration", expirationTime.toString());
		} catch (error) {
			console.error("Failed to save token:", error);
		}
	};

	return (
		<Layout>
			<Card className="w-full max-w-md mx-auto bg-gray-800 text-gray-100">
				<CardContent className="p-6">
					<p className="text-center text-lg">Processing login...</p>
				</CardContent>
			</Card>
			<ToastContainer />
		</Layout>
	);
}

// src/components/AniListRedirect.vue
<script>
export default {
  name: 'AniListRedirect',
  mounted() {
    const urlHash = new URL(window.location.href).hash;
    const accessToken = urlHash.split('=')[1];

    if (accessToken) {
      // Store the access token securely
      localStorage.setItem('anilistToken', accessToken)

      // Save the token with a 24-hour expiration time
      this.saveToken(accessToken);

      // Redirect the user to another page
      this.$router.push('/custom-list-manager/anilist-login')
    } else {
      // Handle the error
      console.error('No access token found in URL hash')
    }
  },
  methods: {
    saveToken(accessToken) {
      // Save the access token to local storage
      localStorage.setItem('anilistToken', accessToken);

      // Set the expiration time to the current time plus 24 hours
      const expirationTime = new Date().getTime() + 24 * 60 * 60 * 1000;
      localStorage.setItem('anilistTokenExpiration', expirationTime.toString());
    }
  }
}
</script>
